networks:
  service-abonents-dev:
    driver: bridge
services:
  app:
    container_name: serviceAbonents
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    networks:
      - service-abonents-dev
    depends_on:
      - serviceAbonents_db
  serviceAbonents_db:
    container_name: serviceAbonents_db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ServiceAbonents_AT
    ports:
      - "5431:5432"
    networks:
      - service-abonents-dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: